# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SCodeScanner
tagline:          'A python based Tool'
description:      'Finding Vulnerability with SCodeScanner. <br>Made by <a href="https://twitter.com/agrawalsmart7" target="_blank">@agrawalsmart7</a>.'
url:              https://scodescanner.info
baseurl:          https://scodescanner.info/

author:
  name:           'Utkarsh Agrawal'
  url:            https://twitter.com/agrawalsmart7
  email:          agrawalsmart7@gmail.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/agrawalsmart7/scodescanner
