# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SCodeScanner
tagline:          'A python based Tool'
description:      'Finding Vulnerability with SCodeScanner. Made by <a href="https://twitter.com/agrawalsmart7" target="_blank">@agrawalsmart7</a>.'
url:              http://scodescanner.info
baseurl:          http://scodescanner.info/

author:
  name:           'Utkarsh Agrawal'
  url:            https://twitter.com/agrawalsmart7

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/agrawalsmart7/scodescanner
